algoritmo "calcula-media"

var
   p1, p2, p3, p4 media: real

inicio

      escreval("calcula méda final")
      escreval("insira a nota da p1: ")
      leia(p1)
      escreval ("insira a nota da p2: ")
      leia(p2)
      escreval("insira a nota da p3 : ")
      leia(p3)
      escreval("insira a nota da p4 : ")
      leia(p4)
      //calcula a media
      media <- (p1+p2+p3+p4)/4
      escreval("O resultado final das provas: ", media)
      

fimalgoritmo
